### ISSUE TITLE
Ref COCO datasets can not be downloaded

### ISSUE THREAD

**Issue by wzic** [DerrickWang005/CRIS.pytorch#10]
Hi! I have tried to download the 3 Ref COCO datasets  by the link, but can not succeed. Are there any other ways to get the datasets?

**Comment by Elfsong** [comment]
https://web.archive.org/web/20220413011817/https://bvisionweb1.cs.unc.edu/licheng/referit/data/refclef.zip
https://web.archive.org/web/20220413011718/https://bvisionweb1.cs.unc.edu/licheng/referit/data/refcoco.zip
https://web.archive.org/web/20220413011656/https://bvisionweb1.cs.unc.edu/licheng/referit/data/refcoco+.zip
https://web.archive.org/web/20220413012904/https://bvisionweb1.cs.unc.edu/licheng/referit/data/refcocog.zip
