### ISSUE TITLE
IoU reported is oIoU or mIoU ?

### ISSUE THREAD

**Issue by qiulesun** [DerrickWang005/CRIS.pytorch#12]
Nice work !
In terms of IoU reported in CRIS, the IoU is overall intersection-over-union (oIoU) or mean intersection-over-union (mIoU) metric?
In the released code, the mIoU metric seems to be calculated for comparisons with SOTA in all tables in CRIS paper.

**Comment by DerrickWang005** [comment]
mIoU

**Comment by qiulesun** [comment]
@DerrickWang005 As far as I know, current SOTAs mainly report oIoU value for comparisons. So do you consider providing corresponding  oIoU values ?
