### ISSUE TITLE
Why set max_length to 17, 22 instead of default value?

### ISSUE THREAD

**Issue by Norwa9** [DerrickWang005/CRIS.pytorch#14]
Hi , I'm new to the Referring Image Segmentation area, could you explain the reason for this? 
Thank you for that!

**Comment by DerrickWang005** [comment]
We counted the length of sentences in different datasets and got the max_length for different datasets. Besides, to save computing resources, we do not use the default length. 77 is too long for these datasets.

**Comment by Norwa9** [comment]
> We count the length of sentences in different datasets and get the max_length for different datasets. Besides, to save computing resources, we do not use the default length. 77 is too long for these datasets.

OK I see, Thank you for fast reply!
