### ISSUE TITLE
How the reported performance results are selected?

### ISSUE THREAD

**Issue by Huntersxsx** [DerrickWang005/CRIS.pytorch#15]
Hello, thanks for your great work! I have some concerns about how the results are selected.
Take dataset RefCOCO for example, as for the different sets: val, test A, and test B, I want to know if you train different checkpoints for these sets according to different val_lmdb configs,  or if you only train one checkpoint as you have given in the config folder, and use the same checkpoint to test on three sets?
Looking forward to your reply!

**Comment by DerrickWang005** [comment]
using different checkpoints for different validation sets
