### ISSUE TITLE
Evaluation code run error: ValueError: operands could not be broadcast together with shapes (480,640) (640,427)

### ISSUE THREAD

**Issue by WuHenry-0609** [DerrickWang005/CRIS.pytorch#18]
**I trained a best_model.pth according to the instructions in github, but after entering the evaluation instructions, an error occurred: ValueError: operands could not be broadcast together with shapes (480,640) (640,427)**

**The error message is as follows:**
'''
2023-11-09 22:21:31 | INFO     | __main__:76 - => loading checkpoint 'exp/refcoco/CRIS_R50/best_model.pth'
2023-11-09 22:21:32 | INFO     | __main__:79 - => loaded checkpoint 'exp/refcoco/CRIS_R50/best_model.pth'
Inference::   0%|                                                          | 0/3811 [00:02<?, ?it/s]
2023-11-09 22:21:35 | ERROR    | __main__:90 - An error has been caught in function '<module>', process 'MainProcess' (844605), thread 'MainThread' (139931839529792):
Traceback (most recent call last):

> File "test.py", line 90, in <module>
    main()
    └ <function main at 0x7f4343b14e50>

  File "test.py", line 86, in main
    inference(test_loader, model, args)
    │         │            │      └ CfgNode({'dataset': 'refcoco', 'train_lmdb': 'datasets/lmdb/refcoco/train.lmdb', 'train_split': 'train', 'val_lmdb': 'dataset...
    │         │            └ DataParallel(
    │         │                (module): CRIS(
    │         │                  (backbone): CLIP(
    │         │                    (visual): ModifiedResNet(
    │         │                      (conv1): Conv2d(3, 32, kernel_s...
    │         └ <torch.utils.data.dataloader.DataLoader object at 0x7f4343ac32b0>
    └ <function inference at 0x7f4343b06e50>

  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<torch.utils.data.dataloader.DataLoader object at 0x7f4343ac32b0>, DataParallel(
           │         (module): CRIS(
           │           (backbone): CLIP(
           │          ...
           └ <function inference at 0x7f4343b06dc0>

  File "/root/autodl-tmp/CRIS.pytorch/engine/engine.py", line 187, in inference
    inter = np.logical_and(pred, mask)
            │  │           │     └ array([[0., 0., 0., ..., 0., 0., 0.],
            │  │           │              [0., 0., 0., ..., 0., 0., 0.],
            │  │           │              [0., 0., 0., ..., 0., 0., 0.],
            │  │           │              ...,...
            │  │           └ array([[False, False, False, ..., False, False, False],
            │  │                    [False, False, False, ..., False, False, False],
            │  │                    [False...
            │  └ <ufunc 'logical_and'>
            └ <module 'numpy' from '/root/miniconda3/lib/python3.8/site-packages/numpy/__init__.py'>

ValueError: operands could not be broadcast together with shapes (480,640) (640,427)
'''

UPDATE: Thank you all for your attention! I have solved this problem myself and will close this issue.

**Comment by lcl-git-3d** [comment]
Hi，have you solved this problem？

**Comment by Dharneeshcr7** [comment]
Hi, Did u try truncating the last row,column and tried it ?

**Comment by tubixiansheng** [comment]
Hello, I would like to know why the error AttributeError: module 'pyarrow' has no attribute 'deserialize' is reported, and what should be the correct version?
