### ISSUE TITLE
ProcessExitedException caused by SIGKILL

### ISSUE THREAD

**Issue by lyu-yx** [DerrickWang005/CRIS.pytorch#19]
When I excute `python -u train.py --config config/refcoco/cris_r50.yaml`, there is an exception occured:

2023-11-29 06:51:23.492 | ERROR    | __main__:<module>:224 - An error has been caught in function '<module>', process 'MainProcess' (524921), thread 'MainThread' (22521945637824):
Traceback (most recent call last):

  > File "train.py", line 224, in <module>
      main()
      └ <function main at 0x147b5e2a7280>
  
    File "train.py", line 62, in main
      mp.spawn(main_worker, nprocs=args.ngpus_per_node, args=(args, ))
      │  │     │                   │                          └ CfgNode({'dataset': 'refcoco', 'train_lmdb': 'datasets/lmdb/refcoco/train.lmdb', 'train_split': 'train', 'val_lmdb': 'dataset...
      │  │     │                   └ CfgNode({'dataset': 'refcoco', 'train_lmdb': 'datasets/lmdb/refcoco/train.lmdb', 'train_split': 'train', 'val_lmdb': 'dataset...
      │  │     └ <function main_worker at 0x147b5e2a7550>
      │  └ <function spawn at 0x147b64ccd670>
      └ <module 'torch.multiprocessing' from '/ext3/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/__init__.py'>
  
    File "/ext3/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
      return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
             │               │   │     │       │     └ False
             │               │   │     │       └ True
             │               │   │     └ 1
             │               │   └ (CfgNode({'dataset': 'refcoco', 'train_lmdb': 'datasets/lmdb/refcoco/train.lmdb', 'train_split': 'train', 'val_lmdb': 'datase...
             │               └ <function main_worker at 0x147b5e2a7550>
             └ <function start_processes at 0x147b64ccd3a0>
    File "/ext3/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
      while not context.join():
                │       └ <function ProcessContext.join at 0x147b64ccd550>
                └ <torch.multiprocessing.spawn.ProcessContext object at 0x147b5e235340>
    File "/ext3/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 130, in join
      raise ProcessExitedException(
            └ <class 'torch.multiprocessing.spawn.ProcessExitedException'>
  
    torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGKILL

I doubt this error occurs because of the version conflict and I have tried python 3.8.15 with pytorch1.9+cuda10.2 and pytorch1.8_cuda10.2. But this error still exist. Have anyone met this before or can the authors release their specific package version used in this  repo? @DerrickWang005  @aniki-ly

**Comment by lcl-git-3d** [comment]
Hi，have you met this problem when run evaluation code.
Evaluation code run error: ValueError: operands could not be broadcast together with shapes (480,640) (640,427)
