### ISSUE TITLE
pyarrow error

### ISSUE THREAD

**Issue by Dharneeshcr7** [DerrickWang005/CRIS.pytorch#20]
AttributeError: module 'pyarrow' has no attribute 'serialize' when trying to prepare dataset.

**Comment by Dharneeshcr7** [comment]
Use Pickle5 as alternative

**Comment by songrise** [comment]
using pickle5 cause an error while loading dataset, see https://github.com/DerrickWang005/CRIS.pytorch/pull/21#issuecomment-1975675121. Should use either pyarrow or pickle5 consistently.
