### ISSUE TITLE
PLEASE MAKE YOUR TRAINING INSTRUCTIONS CLEAR

### ISSUE THREAD

**Issue by sparshgarg23** [DerrickWang005/CRIS.pytorch#23]
It seems that before executing the code,you need to call wandb login.
please include this in readme.the purpose of open sourcing code repositories is to ensure that they are readable and can be understood by readers.If your purpose was to just publish a paper then you shouldn't have bothered open sourcing the code.

**Comment by DerrickWang005** [comment]
I update this issue in readme. Thanks.
