### ISSUE TITLE
Training the model from scratch fails

### ISSUE THREAD

**Issue by saunair** [DerrickWang005/CRIS.pytorch#6]
Hi @DerrickWang005 I'm trying to train the code from scratch, but it expects a `pretrained Resnet50/Resnet101` weights file. Am I running this right? 

```   clip_model = torch.jit.load(cfg.clip_pretrain,
  File "..CRIS.pytorch/env/lib/python3.8/site-packages/torch/jit/_serialization.py", line 152, in load
    raise ValueError("The provided filename {} does not exist".format(f))  # type: ignore[str-bytes-safe]
ValueError: The provided filename pretrain/RN101.pt does not exist```

**Comment by saunair** [comment]
Apologies, didn't know I had to setup the CLIP weights myself. Post that training works.

**Comment by MaslikovEgor** [comment]
@saunair hi! how did you do that correctly?

**Comment by MaslikovEgor** [comment]
I am trying like this:
```
import clip
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load("RN50", device=device)
model.cuda().eval()
PATH = "/content/CRIS.pytorch/pretrain/RN50.pt"
torch.save(model.state_dict(), PATH)
```

but still have error RuntimeError: PytorchStreamReader failed locating file constants.pkl: file not found

**Comment by saunair** [comment]
You've got to pip install clip from ```https://github.com/openai/CLIP``` 
Or you can just download the weights from ```https://github.com/openai/CLIP/blob/main/clip/clip.py#L35```
